# Generated by Django 3.2.15 on 2022-09-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_choice', models.CharField(choices=[], max_length=20)),
                ('booking_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(choices=[(7, '7 Days'), (14, '14 Days'), (21, '21 Days')], default='7', max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Booking Made'), (1, 'Booking Confirmed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
